import os
import time
import matplotlib.pyplot as plt

# File generated by your xApp
CSV_PATH = os.path.expanduser("~/CMOV5/scripts/kpm_results.csv")

def parse_kpm_data(path):
    """Reads the CSV file and groups throughput metrics by time."""
    time_points = []
    dl_throughput = []
    ul_throughput = []
    
    if not os.path.exists(path):
        return time_points, dl_throughput, ul_throughput

    first_ts = None
    with open(path, 'r') as f:
        for line in f:
            parts = line.strip().split(',')
            if len(parts) < 5:
                continue
            try:
                ts = float(parts[0])
                metric = parts[3].strip()
                val = float(parts[4])
                
                if first_ts is None:
                    first_ts = ts
                
                elapsed_seconds = (ts - first_ts) / 1e6
                
                if metric == 'DRB.UEThpDl':
                    time_points.append(elapsed_seconds)
                    dl_throughput.append(val / 1e6)  # Convert to Mbps if needed
                elif metric == 'DRB.UEThpUl':
                    ul_throughput.append(val / 1e6)
            except ValueError:
                continue
                
    return time_points, dl_throughput, ul_throughput

def main():
    print(f"Monitoring {CSV_PATH} for changes... Press Ctrl+C to exit.")
    
    # Enable interactive plotting mode
    plt.ion()
    fig, ax = plt.subplots(figsize=(10, 5))
    
    while True:
        try:
            t, dl, ul = parse_kpm_data(CSV_PATH)
            
            if t:
                ax.clear()
                # We slice the lists to ensure they are the same length if updates are mid-write
                min_len = min(len(t), len(dl))
                ax.plot(t[:min_len], dl[:min_len], label='Downlink Throughput (Mbps)', color='blue', marker='o')
                
                if len(ul) >= min_len:
                    ax.plot(t[:min_len], ul[:min_len], label='Uplink Throughput (Mbps)', color='red', marker='x')
                
                ax.set_title("Real-Time 5G O-RAN Metrics via xApp")
                ax.set_xlabel("Elapsed Time (Seconds)")
                ax.set_ylabel("Throughput (Mbps)")
                ax.legend(loc="upper left")
                ax.grid(True)
                
                plt.draw()
            
            plt.pause(1)  # Refresh plot window every second
            
        except KeyboardInterrupt:
            print("\nMonitoring stopped.")
            break

if __name__ == "__main__":
    main()