import os
import csv
import matplotlib.pyplot as plt

# File generated by your modified xApp
METRICS_FILE = os.path.expanduser("~/flexric/build/xapp_metrics.csv")

def extract_throughput(filepath):
    """Parses the xApp CSV log to extract time and throughput data arrays."""
    timestamps, dl_data, ul_data = [], [], []
    
    if not os.path.isfile(filepath):
        return timestamps, dl_data, ul_data

    start_time = None
    
    with open(filepath, mode='r') as file:
        reader = csv.reader(file)
        next(reader, None) # Skip the header row
        
        for row in reader:
            if len(row) < 5:
                continue
            try:
                current_ts = float(row[0])
                metric_id = row[3].strip()
                value = float(row[4])
                
                # Normalize time to start at 0 seconds
                if start_time is None:
                    start_time = current_ts
                
                elapsed_sec = (current_ts - start_time) / 1e6
                
                # Convert Bps to Mbps and append to respective lists
                if metric_id == 'DRB.UEThpDl':
                    timestamps.append(elapsed_sec)
                    dl_data.append(value / 1e6) 
                elif metric_id == 'DRB.UEThpUl':
                    ul_data.append(value / 1e6)
            except ValueError:
                pass
                
    return timestamps, dl_data, ul_data

def launch_dashboard():
    print(f"[*] Starting live xApp monitor on: {METRICS_FILE}")
    print("[*] Press Ctrl+C to terminate.")
    
    # Change the visual style so it looks completely different from your friend's
    plt.style.use('seaborn-v0_8-darkgrid')
    fig, ax = plt.subplots(figsize=(10, 6))
    
    try:
        while True:
            t_sec, dl_mbps, ul_mbps = extract_throughput(METRICS_FILE)
            
            if t_sec:
                ax.clear()
                # Ensure array lengths match before plotting to prevent crashes mid-write
                safe_len = min(len(t_sec), len(dl_mbps))
                
                ax.plot(t_sec[:safe_len], dl_mbps[:safe_len], 
                        label='DL Throughput (Mbps)', color='#2ca02c', linewidth=2)
                
                if len(ul_mbps) >= safe_len:
                    ax.plot(t_sec[:safe_len], ul_mbps[:safe_len], 
                            label='UL Throughput (Mbps)', color='#ff7f0e', linewidth=2, linestyle='--')
                
                ax.set_title("O-RAN xApp Live Metrics Dashboard", fontsize=14, fontweight='bold')
                ax.set_xlabel("Time Elapsed (Seconds)", fontsize=12)
                ax.set_ylabel("Throughput (Mbps)", fontsize=12)
                ax.legend(loc="upper right")
                
                plt.tight_layout()
                plt.pause(1.0)
            else:
                plt.pause(1.0)
                
    except KeyboardInterrupt:
        print("\n[*] Dashboard closed.")
        plt.close()

if __name__ == "__main__":
    launch_dashboard()